services:
  backend:
    build: .
    volumes:
      - "./results:/src/results"
    ports:
      - "8888:8888"
    command: jupyter-notebook --no-browser --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' --allow-root